/**
 * Vimeo Service
 * Handles OAuth, account management, and video upload to Vimeo.
 *
 * Token storage note: access_token_vault_id stores the raw access token directly
 * in this implementation. In a production hardening pass, replace with Supabase
 * Vault secret IDs so tokens are encrypted at rest.
 */

import { createClient } from '@/utils/supabase/server';
import type { CoachExternalAccount, ExternalVideoShare, PrivacySetting } from '@/types/communication';

// ============================================================================
// Constants
// ============================================================================

const VIMEO_AUTH_URL = 'https://api.vimeo.com/oauth/authorize';
const VIMEO_TOKEN_URL = 'https://api.vimeo.com/oauth/access_token';
const VIMEO_API_BASE = 'https://api.vimeo.com';
const VIMEO_API_ACCEPT = 'application/vnd.vimeo.*+json;version=3.4';

// ============================================================================
// OAuth
// ============================================================================

/**
 * Build the Vimeo OAuth authorization URL to redirect the user to.
 * Requires VIMEO_CLIENT_ID and VIMEO_REDIRECT_URI environment variables.
 *
 * @param state - CSRF state token generated by the initiating route
 * @returns Full Vimeo authorization URL with query parameters
 */
export function getVimeoAuthUrl(state: string): string {
  const clientId = process.env.VIMEO_CLIENT_ID;
  const redirectUri = process.env.VIMEO_REDIRECT_URI;

  if (!clientId || !redirectUri) {
    throw new Error('Vimeo OAuth not configured (VIMEO_CLIENT_ID, VIMEO_REDIRECT_URI)');
  }

  const params = new URLSearchParams({
    response_type: 'code',
    client_id: clientId,
    redirect_uri: redirectUri,
    state,
    scope: 'upload video_files public private',
  });

  return `${VIMEO_AUTH_URL}?${params.toString()}`;
}

export interface VimeoTokenResult {
  accessToken: string;
  user: { uri: string; name: string };
  scope: string;
}

/**
 * Exchange a Vimeo authorization code for an access token.
 * Called once from the OAuth callback route after Vimeo redirects back.
 *
 * @param code - The authorization code from the Vimeo callback query string
 * @returns Access token, Vimeo user metadata, and granted scope string
 */
export async function exchangeCodeForToken(code: string): Promise<VimeoTokenResult> {
  const clientId = process.env.VIMEO_CLIENT_ID;
  const clientSecret = process.env.VIMEO_CLIENT_SECRET;
  const redirectUri = process.env.VIMEO_REDIRECT_URI;

  if (!clientId || !clientSecret || !redirectUri) {
    throw new Error('Vimeo OAuth credentials not configured (VIMEO_CLIENT_ID, VIMEO_CLIENT_SECRET, VIMEO_REDIRECT_URI)');
  }

  const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');

  const response = await fetch(VIMEO_TOKEN_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': VIMEO_API_ACCEPT,
      'Authorization': `basic ${credentials}`,
    },
    body: JSON.stringify({
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Vimeo token exchange failed (${response.status}): ${errorText}`);
  }

  const data = await response.json();

  return {
    accessToken: data.access_token as string,
    user: data.user as { uri: string; name: string },
    scope: data.scope as string,
  };
}

// ============================================================================
// Account Management
// ============================================================================

/**
 * Persist a Vimeo connection in coach_external_accounts.
 * Upserts so that reconnecting an already-linked account refreshes credentials.
 *
 * @param coachId - Supabase auth user ID of the coach
 * @param accessToken - Raw Vimeo access token (stored in access_token_vault_id)
 * @param accountId - Vimeo user ID extracted from the user URI
 * @param accountName - Vimeo display name for the account
 */
export async function saveVimeoConnection(
  coachId: string,
  accessToken: string,
  accountId: string,
  accountName: string,
): Promise<void> {
  const supabase = await createClient();

  const { error } = await supabase
    .from('coach_external_accounts')
    .upsert(
      {
        coach_id: coachId,
        platform: 'vimeo',
        platform_account_id: accountId,
        platform_account_name: accountName,
        // TODO(hardening): replace raw token with a Supabase Vault secret ID
        access_token_vault_id: accessToken,
        status: 'active',
        connected_at: new Date().toISOString(),
      },
      { onConflict: 'coach_id,platform' },
    );

  if (error) {
    throw new Error(`Failed to save Vimeo connection: ${error.message}`);
  }
}

/**
 * Retrieve the coach's Vimeo account record, or null if not connected.
 *
 * @param coachId - Supabase auth user ID of the coach
 */
export async function getVimeoAccount(coachId: string): Promise<CoachExternalAccount | null> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from('coach_external_accounts')
    .select('*')
    .eq('coach_id', coachId)
    .eq('platform', 'vimeo')
    .single();

  if (error) {
    // PGRST116 = no rows found — not an error condition for this query
    if (error.code === 'PGRST116') return null;
    throw new Error(`Failed to fetch Vimeo account: ${error.message}`);
  }

  return data;
}

/**
 * Mark a Vimeo account as disconnected. Does not delete the record so that
 * historical external_video_shares retain their coach link.
 *
 * @param coachId - Supabase auth user ID of the coach
 */
export async function disconnectVimeo(coachId: string): Promise<void> {
  const supabase = await createClient();

  const { error } = await supabase
    .from('coach_external_accounts')
    .update({ status: 'disconnected' })
    .eq('coach_id', coachId)
    .eq('platform', 'vimeo');

  if (error) {
    throw new Error(`Failed to disconnect Vimeo: ${error.message}`);
  }
}

/**
 * Retrieve the raw Vimeo access token for an active coach connection.
 * Returns null if the account is missing, disconnected, or expired.
 *
 * @param coachId - Supabase auth user ID of the coach
 */
export async function getVimeoAccessToken(coachId: string): Promise<string | null> {
  const supabase = await createClient();

  const { data } = await supabase
    .from('coach_external_accounts')
    .select('access_token_vault_id, status')
    .eq('coach_id', coachId)
    .eq('platform', 'vimeo')
    .eq('status', 'active')
    .single();

  if (!data) return null;

  // TODO(hardening): retrieve from Supabase Vault using data.access_token_vault_id as the secret ID
  return data.access_token_vault_id;
}

// ============================================================================
// Video Upload
// ============================================================================

export interface VimeoUploadInput {
  coachId: string;
  teamId: string;
  sourceType: ExternalVideoShare['source_type'];
  sourceId: string;
  title: string;
  description?: string;
  privacySetting: PrivacySetting;
  confirmationText: string;
  /** Publicly accessible URL that Vimeo will pull the video from */
  videoUrl: string;
}

/** Maps our PrivacySetting values to Vimeo's privacy.view values */
const VIMEO_PRIVACY_MAP: Record<PrivacySetting, string> = {
  public: 'anybody',
  unlisted: 'unlisted',
  private: 'nobody',
};

/**
 * Initiate a video upload to Vimeo using the pull approach (Vimeo fetches from URL).
 * Creates an external_video_shares record, then calls the Vimeo API.
 * On failure the share record is marked 'failed' before re-throwing.
 *
 * Watermark is always applied — this is mandatory and non-configurable by callers.
 *
 * @param input - Upload parameters including coach, team, source, and Vimeo metadata
 * @returns The external_video_shares row ID for status polling
 */
export async function uploadToVimeo(input: VimeoUploadInput): Promise<string> {
  const supabase = await createClient();

  const accessToken = await getVimeoAccessToken(input.coachId);
  if (!accessToken) {
    throw new Error('Vimeo account not connected or token expired');
  }

  // Create the share record first so we have an ID to update through the lifecycle
  const { data: share, error: shareError } = await supabase
    .from('external_video_shares')
    .insert({
      coach_id: input.coachId,
      team_id: input.teamId,
      source_type: input.sourceType,
      source_id: input.sourceId,
      platform: 'vimeo',
      title: input.title,
      description: input.description ?? null,
      privacy_setting: input.privacySetting,
      watermark_applied: true,
      upload_status: 'pending',
      upload_progress: 0,
      confirmation_text: input.confirmationText,
    })
    .select('id')
    .single();

  if (shareError || !share) {
    throw new Error(`Failed to create external share record: ${shareError?.message}`);
  }

  try {
    await supabase
      .from('external_video_shares')
      .update({ upload_status: 'uploading' })
      .eq('id', share.id);

    const vimeoResponse = await fetch(`${VIMEO_API_BASE}/me/videos`, {
      method: 'POST',
      headers: {
        'Authorization': `bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'Accept': VIMEO_API_ACCEPT,
      },
      body: JSON.stringify({
        upload: {
          approach: 'pull',
          link: input.videoUrl,
        },
        name: input.title,
        description: input.description ?? '',
        privacy: {
          view: VIMEO_PRIVACY_MAP[input.privacySetting],
          embed: 'public',
        },
      }),
    });

    if (!vimeoResponse.ok) {
      const errorText = await vimeoResponse.text();
      throw new Error(`Vimeo API error (${vimeoResponse.status}): ${errorText}`);
    }

    const vimeoData = await vimeoResponse.json();
    // Vimeo returns a URI like /videos/123456789
    const videoUri: string = vimeoData.uri ?? '';
    const videoId = videoUri.split('/').pop() ?? '';
    const externalUrl: string | null = vimeoData.link ?? null;

    await supabase
      .from('external_video_shares')
      .update({
        upload_status: 'processing',
        external_video_id: videoId || null,
        external_url: externalUrl,
        upload_progress: 100,
      })
      .eq('id', share.id);

    return share.id;
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Unknown upload error';

    await supabase
      .from('external_video_shares')
      .update({
        upload_status: 'failed',
        upload_error: errorMessage,
      })
      .eq('id', share.id);

    throw err;
  }
}

// ============================================================================
// Share Retrieval & Status
// ============================================================================

/**
 * Get all external video shares for a team, ordered newest-first.
 *
 * @param teamId - The team to query shares for
 */
export async function getExternalShares(teamId: string): Promise<ExternalVideoShare[]> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from('external_video_shares')
    .select('*')
    .eq('team_id', teamId)
    .order('created_at', { ascending: false });

  if (error) {
    throw new Error(`Failed to fetch external shares: ${error.message}`);
  }

  return data ?? [];
}

/**
 * Poll the Vimeo API for the current transcode status of an uploaded video.
 * Updates the external_video_shares record as the status progresses.
 * Returns the UploadStatus string for the caller to surface in the UI.
 *
 * @param shareId - The external_video_shares row ID
 */
export async function checkVimeoUploadStatus(shareId: string): Promise<string> {
  const supabase = await createClient();

  const { data: share } = await supabase
    .from('external_video_shares')
    .select('external_video_id, coach_id, upload_status')
    .eq('id', shareId)
    .single();

  if (!share) return 'pending';

  // Already in a terminal state — no need to poll Vimeo
  if (share.upload_status === 'complete' || share.upload_status === 'failed') {
    return share.upload_status;
  }

  if (!share.external_video_id) return share.upload_status ?? 'pending';

  const accessToken = await getVimeoAccessToken(share.coach_id);
  if (!accessToken) {
    return 'failed';
  }

  const response = await fetch(`${VIMEO_API_BASE}/videos/${share.external_video_id}`, {
    headers: {
      'Authorization': `bearer ${accessToken}`,
      'Accept': VIMEO_API_ACCEPT,
    },
  });

  if (!response.ok) {
    return 'failed';
  }

  const data = await response.json();
  const transcodeStatus: string | undefined = data.transcode?.status;

  if (transcodeStatus === 'complete') {
    await supabase
      .from('external_video_shares')
      .update({
        upload_status: 'complete',
        external_url: data.link ?? null,
        published_at: new Date().toISOString(),
      })
      .eq('id', shareId);

    return 'complete';
  }

  if (transcodeStatus === 'error') {
    await supabase
      .from('external_video_shares')
      .update({
        upload_status: 'failed',
        upload_error: 'Vimeo transcoding failed',
      })
      .eq('id', shareId);

    return 'failed';
  }

  // Still in progress
  return 'processing';
}
