-- Migration 023: Game Strategy Assistant System
-- Adds tables for strategic insights, questions, and preparation checklists

-- ============================================================================
-- Strategic Insights Cache
-- Stores computed insights to avoid re-computation
-- ============================================================================
CREATE TABLE strategic_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  game_id UUID REFERENCES games(id) ON DELETE CASCADE,
  opponent_name TEXT,

  -- Insight category
  category TEXT NOT NULL CHECK (category IN (
    'opponent_tendency',
    'own_strength',
    'own_weakness',
    'matchup_advantage',
    'matchup_concern',
    'personnel_consideration',
    'situational_recommendation'
  )),

  -- Insight content
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  priority INTEGER CHECK (priority BETWEEN 1 AND 5), -- 1=highest
  confidence_score DECIMAL(3,2) CHECK (confidence_score BETWEEN 0 AND 1),

  -- Supporting data
  supporting_stats JSONB,
  related_plays TEXT[],

  -- Rule-based or AI-generated
  generation_method TEXT CHECK (generation_method IN ('rule_based', 'ai_assisted', 'manual')),

  -- Lifecycle
  is_active BOOLEAN DEFAULT true,
  acknowledged_by_user_id UUID REFERENCES auth.users(id),
  acknowledged_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_strategic_insights_team_game ON strategic_insights(team_id, game_id);
CREATE INDEX idx_strategic_insights_category ON strategic_insights(category);
CREATE INDEX idx_strategic_insights_priority ON strategic_insights(priority);

COMMENT ON TABLE strategic_insights IS 'Stores strategic insights generated for game preparation';
COMMENT ON COLUMN strategic_insights.category IS 'Type of insight: opponent tendency, team strength/weakness, matchup analysis, etc.';
COMMENT ON COLUMN strategic_insights.priority IS '1=critical, 5=low priority';
COMMENT ON COLUMN strategic_insights.generation_method IS 'How insight was generated: rule_based (stats), ai_assisted (future), manual (coach added)';

-- ============================================================================
-- Strategic Questions
-- Coach reflection questions to guide thinking
-- ============================================================================
CREATE TABLE strategic_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  game_id UUID REFERENCES games(id) ON DELETE CASCADE,

  -- Question metadata
  category TEXT NOT NULL CHECK (category IN (
    'offensive_strategy',
    'defensive_strategy',
    'special_teams',
    'personnel',
    'situational'
  )),
  question_text TEXT NOT NULL,
  sort_order INTEGER,

  -- Response
  coach_response TEXT,
  response_options JSONB,
  responded_at TIMESTAMPTZ,
  responded_by UUID REFERENCES auth.users(id),

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_strategic_questions_team_game ON strategic_questions(team_id, game_id);
CREATE INDEX idx_strategic_questions_category ON strategic_questions(category);

COMMENT ON TABLE strategic_questions IS 'Strategic questions to guide coach thinking during game prep';
COMMENT ON COLUMN strategic_questions.response_options IS 'Optional multiple choice options as JSON array';

-- ============================================================================
-- Preparation Checklist
-- Game week preparation tracking
-- ============================================================================
CREATE TABLE preparation_checklist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  game_id UUID NOT NULL REFERENCES games(id) ON DELETE CASCADE,

  -- Checklist item
  category TEXT NOT NULL,
  item_text TEXT NOT NULL,
  priority INTEGER CHECK (priority BETWEEN 1 AND 3), -- 1=must do, 2=should do, 3=nice to have
  sort_order INTEGER,

  -- Completion tracking
  is_completed BOOLEAN DEFAULT false,
  completed_by UUID REFERENCES auth.users(id),
  completed_at TIMESTAMPTZ,
  notes TEXT,

  -- Auto-generated or manual
  is_auto_generated BOOLEAN DEFAULT true,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_preparation_checklist_team_game ON preparation_checklist(team_id, game_id);
CREATE INDEX idx_preparation_checklist_priority ON preparation_checklist(priority);

COMMENT ON TABLE preparation_checklist IS 'Game week preparation checklist items';
COMMENT ON COLUMN preparation_checklist.priority IS '1=must do, 2=should do, 3=nice to have';
COMMENT ON COLUMN preparation_checklist.is_auto_generated IS 'True if generated by system, false if manually added by coach';

-- ============================================================================
-- Opponent Scouting Reports (Enhanced)
-- Add fields to games table for scouting
-- ============================================================================
ALTER TABLE games
  ADD COLUMN IF NOT EXISTS opponent_team_id UUID REFERENCES teams(id),
  ADD COLUMN IF NOT EXISTS scouting_report_summary TEXT,
  ADD COLUMN IF NOT EXISTS scouting_completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS scouting_completed_by UUID REFERENCES auth.users(id);

COMMENT ON COLUMN games.opponent_team_id IS 'Reference to another team in system if scouting them';
COMMENT ON COLUMN games.scouting_report_summary IS 'Brief summary of opponent scouting findings';

-- ============================================================================
-- RLS Policies
-- ============================================================================
ALTER TABLE strategic_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategic_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE preparation_checklist ENABLE ROW LEVEL SECURITY;

-- Strategic insights: Team members can view/insert/update
CREATE POLICY strategic_insights_team_access ON strategic_insights
  FOR ALL
  USING (
    team_id IN (
      SELECT team_id FROM team_memberships WHERE user_id = auth.uid()
      UNION
      SELECT id FROM teams WHERE user_id = auth.uid()
    )
  );

-- Strategic questions: Team members can view/update responses
CREATE POLICY strategic_questions_team_access ON strategic_questions
  FOR ALL
  USING (
    team_id IN (
      SELECT team_id FROM team_memberships WHERE user_id = auth.uid()
      UNION
      SELECT id FROM teams WHERE user_id = auth.uid()
    )
  );

-- Preparation checklist: Team members can view/update
CREATE POLICY preparation_checklist_team_access ON preparation_checklist
  FOR ALL
  USING (
    team_id IN (
      SELECT team_id FROM team_memberships WHERE user_id = auth.uid()
      UNION
      SELECT id FROM teams WHERE user_id = auth.uid()
    )
  );

-- ============================================================================
-- Database Functions for Analytics
-- ============================================================================

-- Get opponent tendencies by down and distance
CREATE OR REPLACE FUNCTION get_opponent_tendencies(
  p_opponent_name TEXT,
  p_team_id UUID
)
RETURNS TABLE (
  down INTEGER,
  distance_range TEXT,
  run_pct DECIMAL,
  pass_pct DECIMAL,
  play_count INTEGER,
  avg_yards DECIMAL,
  success_rate DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    pi.down,
    CASE
      WHEN pi.distance <= 3 THEN 'short'
      WHEN pi.distance <= 7 THEN 'medium'
      ELSE 'long'
    END as distance_range,
    ROUND(AVG(CASE WHEN pi.play_type = 'run' THEN 1.0 ELSE 0.0 END) * 100, 1) as run_pct,
    ROUND(AVG(CASE WHEN pi.play_type = 'pass' THEN 1.0 ELSE 0.0 END) * 100, 1) as pass_pct,
    COUNT(*)::INTEGER as play_count,
    ROUND(AVG(pi.yards_gained), 1) as avg_yards,
    ROUND(AVG(CASE WHEN pi.success THEN 1.0 ELSE 0.0 END) * 100, 1) as success_rate
  FROM play_instances pi
  JOIN videos v ON pi.video_id = v.id
  JOIN games g ON v.game_id = g.id
  WHERE g.opponent ILIKE '%' || p_opponent_name || '%'
    AND g.team_id = p_team_id
    AND g.is_opponent_game = true
    AND pi.down IS NOT NULL
    AND pi.distance IS NOT NULL
  GROUP BY pi.down, distance_range
  ORDER BY pi.down, distance_range;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_opponent_tendencies IS 'Analyzes opponent play-calling tendencies by down and distance';
